# Site settings
title: CopyPasteStd
blog_title: CODE / DIY
header-img: img/home-bg.jpg
email: copypastestd@gmail.com
copyright_name: CopyPaste
description: "Copy Paste ... Profit"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
url: http://shikherverma.com #only used in disque comments for now
disqus_url: shikherverma.com # disque comments are broken if you send http:// along with url
github_username: copypastestd
link: RomeoND

collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
